apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: default
  labels:
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      volumes:
      - name: base-shared-data
        emptyDir: {}
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: base-shared-data
          mountPath: /var/run/docker.sock
        env:
        - name: KAFKA_CREATE_TOPICS
          value: "create-user:1:1"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "16000"
