--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    environment: dev
    tier: metadata
  name: journal-service
spec: 
  selector: 
    matchLabels: 
      environment: dev
      tier: metadata
  template: 
    metadata: 
      labels: 
        environment: dev
        tier: metadata
    spec: 
      containers: 
        - image: "greenfield0000/journal-service:1.0.0"
          name: journal-service
          ports: 
            - containerPort: 8083

