apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    environment: dev
    tier: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

