apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-db-pv-claim
  labels:
    environment: dev
    tier: metadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

