apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    environment: dev
    tier: personal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

