apiVersion: v1
kind: Service
metadata:
  name: personal-db
  labels:
    environment: dev
    tier: personal
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    environment: dev
    tier: personal
  clusterIP: None
